### ISSUE TITLE
HLE/HLE.cpp:738 Unimplemented HLE function scePowerIdleTimerEnable

### ISSUE THREAD

**Issue by BrownNPC** [jcnmsg/LuaDEV-R0-PSP#8]
```
53:32:293 LuaDriver    E[HLE]: HLE/HLE.cpp:738 Unimplemented HLE function scePowerIdleTimerEnable
53:32:294 user_main    E[FILESYS]: FileSystems/DirectoryFileSystem.cpp:58 DirectoryFileSystem::OpenFile('/recovery.lua'): FAILED, 2 - access = 1 ''
53:32:306 user_main    E[FILESYS]: FileSystems/DirectoryFileSystem.cpp:58 DirectoryFileSystem::OpenFile('/recovery.lue'): FAILED, 2 - access = 1 ''
53:32:316 user_main    E[FILESYS]: FileSystems/DirectoryFileSystem.cpp:58 DirectoryFileSystem::OpenFile('/script.lue'): FAILED, 2 - access = 1 ''
```

So i was trying to run this using ppsspp but it doesn't work. What build of ppsspp did you use to test this app?

**Comment by jcnmsg** [comment]
Just tried it on a range of different versions, from 1.17.1 to as far back as 1.14.1 (on Linux) and it doesn't seem to work. It did work fine up until mid-2021 when the last PR was merged so you might want to try whatever version was considered latest back then and I'll look into this when I have the time. Worth mentioning that I don't get the exact same errors as you do, but the interpreter still crashes. I can also test on Windows later, just in case.

Note that without the original source code for the interpreter, unless the problem originates from a new setting we can disable on the latest versions, it's gonna be hard to get this running again without getting PPSSPP developers onboard. That said, maybe it would be wise to open an issue there and see if someone has stumbled upon a similar issue?

**Comment by BrownNPC** [comment]
Yeah It's a bug with the latest ppsspp. I ran 1.9.3 and it works fine.
